### PR TITLE
FIX: resolve Show Threshold and Roi name issue in the new ImageJ verions

### LINKED ISSUE #8: Show Thresholds fail on the latest Fiji
image
It freezes on Win10 Fiji 2.1.1
@westonstauffer

### LINKED ISSUE #9: Duplicate and incorrect names in latest version of Fiji
In macOS and Fiji version 2.1.0 (1.53c), identification of ROIs results in duplicates within the ROI manager, and names of ROIs no longer display cell number as in data tables. The order of ROIs in the manager, and in data tables is still congruent.
EzColocalization_ROI_selected
EzColocalization_duplicate_ROI
EzColocalization_new_ROI

### PR DESCRIPTION
**Pull request by shenghuanjie**
Fixes #8 Fixes #9

Change file from CRLF to LF
Remove unused imports and reorganize imports

### CODE REVIEW

**Comment by shenghuanjie** [comment]
@westonstauffer. Please give a thumb up if it is working for you.

**Comment by westonstauffer** [comment]
Heat maps scaled by "image" and "stack" do not clear outside of ROIs and are identical.
"Image" scaling
image_scaled_heat_map
"Stack" scaling
stack_scaled_heat_map

**Comment by westonstauffer** [comment]
ROIs in manager now have cell numbers but still have duplicates. For example:
Image 1 cell 1
Image1cell1
Image 1 cell 2 is a duplicate of Image 1 cell 1
Image1cell2
Image 1 cell 3 is the true cell 2 in this example
Image1cell3

**Comment by westonstauffer** [comment]
Cell filters other than the pre-watershed filter identify additional incorrect cells for analysis as in this example:

Without cell filters. Yellow outline shows selected cells
No_filters

With pre-watershed filter of 500-Infinity, two cells with >500 pixels are selected and shown in analysis table
pre-watershed_filter

With cell filter 1 set to "Area" and 500-Infinity there are additional cells shown with yellow outline, and additional cells in data table
cell_filter_1

**Comment by shenghuanjie** [comment]
> ROIs in manager now have cell numbers but still have duplicates. For example:

The following change is just a disaster waiting to happen.
ImageJ should not have decreased the visibility of part of a protected function.
What happened recently is the update to `RoiManager` got separated into a private function from the protected `saveResults` we override in `EzColocalization`.
After this change, there is no way for us to have control over the update happening in RoiManager since the new `addToRoiManager` is a private method.
https://github.com/imagej/imagej1/blob/ba4a8ee10f3cbe06393f4046a88bfa67683aedfd/ij/plugin/filter/ParticleAnalyzer.java#L910-L912

**Comment by shenghuanjie** [comment]
> Heat maps scaled by "image" and "stack" do not clear outside of ROIs and are identical.

Are you sure we were clearing the outside of ROIs before for "image" and "stack"?

**Comment by westonstauffer** [comment]
@shenghuanjie Retested and heat map functions are fine

**Comment by westonstauffer** [comment]
> > Heat maps scaled by "image" and "stack" do not clear outside of ROIs and are identical.
> 
> Are you sure we were clearing the outside of ROIs before for "image" and "stack"?

You are right. We didn't clear outside of ROIs in "image" or "stack" scaling. I have found that the "stack" scaling is scaling by the first image in the stack. In this example, Image 1 in a stack has 1/5 its normal intensity and for "cell" and "stack" scaling looks similar:
"image" scaling
Imagescale_1:5intensity
"stack" scaling
Stackscale_1:5intensity

But other images are shifted to mostly maximum values for the "stack" scaling because image 1 had such a lower range for scaling
"stack" scaling
Stackscale
"image" scaling
Imagescale

**Pull request merged**
